### PR TITLE
Add shifttime interpolation outside first and last barcode

### PR DESCRIPTION
**Pull request by danielpollak**

### CODE REVIEW

**Review by wagenadl — CHANGES_REQUESTED** [review]
Extrapolation looks fine, but the interpolation code in lines 1181-1184 doesn't look right. What is "ss1_matched" supposed to be? And isn't it the case that "matchbarcodes" guarantees that len(ss1) = len(ss2) ?

**Comment by danielpollak** [comment]
Hi @wagenadl, I committed the change in the original branch. I'm not sure how this works yet- can you see the change in the commits tab, or do I need to do something on this end?

**Review by wagenadl — CHANGES_REQUESTED** [review]
Hi Dan,
I don't think catastrophic failure to match should be tolerated. Better raise an exception in that case, because it will surely lead to problems down the line. Also, there is no guarantee now that ss1 and ss2 have the same length, and that is not a problem. I may just merge your request and then fix it up.

**Comment by danielpollak** [comment]
I see. Sorry about the len(ss1)==len(ss2), I thought you wanted me to leave the length matching to matchbarcodes. Let me know if you'd prefer I add the exception, it's not clear what the plan is from your last comment.

**Pull request merged**
